name: CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: python-bullseye
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: C:\Users\timcy\Documents\Aicore\Data-Collection-Pipeline\docker\
          file: .\Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/scraper-rottentomatoes
